---
# tasks file for ansible-role-envoy

- name: Ensure envoy image is pulled
  community.docker.docker_image:
    name: "{{ envoy_docker_image }}"
    tag: "{{ envoy_docker_image_tag }}"
    source: pull

- name: Ensure configuration directories are created
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
  loop: "{{ envoy_xds_config }}"

- name: Ensure envoy configuration is copied
  ansible.builtin.template:
    src: "{{ role_path }}/templates/envoy.yaml.j2"
    dest: "{{ envoy_static_conf_path }}"
    owner: "101"
    group: "101"
    mode: 0600
  notify:
    - restart envoy

# - name: xDS debug loop
#   ansible.builtin.debug:
#     msg: "{{ item.data }}"
#   loop: "{{ envoy_xds_config |flatten(levels=1) }}"

# Don't notify to restart. The configuration is reloaded automatically
- name: Ensure xDS configuration is copied
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item.template }}.yaml.j2"
    dest: "{{ item.dest }}"
    owner: "101"
    group: "101"
    mode: 0600
  loop: "{{ envoy_xds_config }}"

# - meta: end_play

- name: Change owner and group of certificates
  ansible.builtin.file:
    path: /etc/letsencrypt/live/
    owner: "101"
    group: "101"
    recurse: true
    mode: 0777

- name: Ensure envoy container runs
  community.docker.docker_container:
    name: "{{ envoy_container_name }}"
    image: "{{ envoy_docker_image }}:{{ envoy_docker_image_tag }}"
    # restart_policy: always
    state: present
    pull: "{{ envoy_upgrade | default(false) | bool }}"
    # restart: yes
    # memory: "{{ envoy_container_memory_limit | default(omit) }}"
    volumes:
      - "{{ envoy_conf_dir }}:/envoy/config:ro"
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "{{ envoy_port }}:8080"
      # - "[::]:{{ envoy_port }}:8080"
      - "{{ envoy_port_ssl }}:4443"
      # - "[::]:{{ envoy_port_ssl }}:4443"
      - "{{ envoy_port_ssl }}:4443/udp"
      # - "[::]:{{ envoy_port_ssl }}:4443/udp"
      - "{{ envoy_admin_port }}:9901"
      # - "[::]:{{ envoy_admin_port }}:9901"
    env:
      ENVOY_UID: "101"
      ENVOY_GID: "101"
    entrypoint: envoy
    command: |
      "--config-path {{ envoy_static_conf_path }}"
    container_default_behavior: no_defaults
    networks: "{{ envoy_networks }}"
    networks_cli_compatible: yes
    network_mode: default
  register: result_container_create
  notify: # -> restart
    - restart envoy
