---
# tasks file for ansible-role-envoy

- name: Ensure envoy image is pulled
  docker_image:
    name: "{{ envoy_docker_image }}"
    tag: "{{ envoy_docker_image_tag }}"
    source: pull

- name: Ensure envoy container is up-to-date
  docker_container:
    name: "{{ envoy_container_name }}"
    image: "{{ envoy_docker_image }}:{{ envoy_docker_image_tag }}"
    pull: "{{ envoy_upgrade | default(false) | bool }}"
  notify:
    - start envoy

# the /envoy/certs dir will be created by volumes later on
- name: Ensure configuration dir is created
  file:
    path: "/envoy/config"
    state: directory
  notify:
    - start envoy

- name: Ensure envoy configuration file is copied
  template:
    src: envoy-custom.yaml.j2
    dest: /envoy/config/envoy-custom.yaml
    owner: "101"
    group: "101"
    mode: 0600
  notify:
    - start envoy

- name: Change owner and group of certificates
  ansible.builtin.file:
    path: /etc/letsencrypt/live/
    owner: "101"
    group: "101"
    recurse: true
    mode: 0777
  notify:
    - start envoy
