---
# handlers file for ansible-role-odoo

- name: Restart Envoy
  command: "docker restart {{ postgres_container_name }}"
  listen: restart envoy

- name: Wait until Envoy starts up
  wait_for:
    port: "{{ envoy_port }}"
    delay: 5
  listen: restart envoy
